package com.java.TicketBookingApp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Info;
import io.swagger.v3.oas.annotations.servers.Server;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@OpenAPIDefinition(
		info=@Info(
				title="TicketBooking API",
				version="1.0.0",
				description="This API will Book and Generate Ticket "
				),
			servers=@Server(
					url="http://localhost:8484/TicketBookingAPI/",
					description="This api deployend in this endpoints"
					)
		
		)
public class TicketBookingAppApplication {

	public static void main(String[] args) {
		SpringApplication.run(TicketBookingAppApplication.class, args);
	}

}
