package com.java.SpringRestApp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

import com.java.SpringRestApp.Service.ICourse;
import com.java.SpringRestApp.Service.Java;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class SpringRestAppApplication {

	public static void main(String[] args) {
		ConfigurableApplicationContext container = SpringApplication.run(SpringRestAppApplication.class, args);
		ICourse course = container.getBean(Java.class);
		course.getTheCourse(43535.3);
	}

}
